### ISSUE TITLE
OTA examples build fails for `arduino:renesas_uno:unor4wifi`

### ISSUE THREAD

**Issue by aentinger** [arduino/ArduinoCore-renesas#121]
I.e. look here https://github.com/arduino/ArduinoCore-renesas/actions/runs/6066057629/job/16469127991?pr=119#step:9:9689 .

@pennam, I'm tagging you since you wrote most of that code, can you please fix the failing build? 🙏

**Comment by aentinger** [comment]
@facchinm ... what do you think, should we cook a new core to resolve this?

**Comment by facchinm** [comment]
In the oven :wink:

**Comment by per1234** [comment]
Fixed by the [1.0.4 release](https://github.com/arduino/ArduinoCore-renesas/releases/tag/1.0.4).
