### ISSUE TITLE
Uno R4 connection failed to Xampp Server

### ISSUE THREAD

**Issue by plcanda** [arduino/ArduinoCore-renesas#132]
I am currently having a problem on my Arduino Uno R4 Wifi in which the original code works perfectly on Arduino Uno Rev2 Wifi, Nano IOT33

Program: Sending Temperature data to Xampp Server
Problem: Cannot connect to SQL Server

**Simple Networking on Uno R4
Result: Connection failed**
[WiFiWebClientRepeating_WifiS3.zip](https://github.com/arduino/ArduinoCore-renesas/files/12602402/WiFiWebClientRepeating_WifiS3.zip)

![image](https://github.com/arduino/ArduinoCore-renesas/assets/129917306/3645f54d-7e8b-466d-9c83-cf7ccfe04ca1)

**Simple Networking on WifiNina Devices
Result: OK**
[WiFiWebClientRepeating_WifiNina.zip](https://github.com/arduino/ArduinoCore-renesas/files/12602409/WiFiWebClientRepeating_WifiNina.zip)
![image](https://github.com/arduino/ArduinoCore-renesas/assets/129917306/f22e829c-b275-4045-9bca-4c7efe15b110)

[https://forum.arduino.cc/t/arduino-uno-r4-wifi-cannot-connect-to-server/1159322](url)

**Comment by facchinm** [comment]
This issue will be fixed as soon as https://github.com/arduino/ArduinoCore-renesas/pull/129 is merged and released

**Comment by per1234** [comment]
Closing as fixed by the merge of https://github.com/arduino/ArduinoCore-renesas/pull/129
