### ISSUE TITLE
C33 SFU OTAUsage example just blinks LEDs?

### ISSUE THREAD

**Issue by JAndrassy** [arduino/ArduinoCore-renesas#152]
The C33 SFU library example [OTAUsage](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/SFU/examples/OTAUsage/OTAUsage.ino), doesn't look like it does what it should do. There is no code to download an update file to FS.

**Comment by pennam** [comment]
Hi @JAndrassy,
The OTAUsage example is included as a reference to show how to build an OTA binary. The intention was to upload the binary to our servers and create another example that downloads the file and performs the update, but we are fixing some issues related to download https://github.com/arduino/ArduinoCore-renesas/pull/134 https://github.com/arduino/ArduinoCore-renesas/pull/151

In the end i've decided to add [this](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/SFU/examples/UpdateFromFile/UpdateFromFile.ino) example that loads the update file directly from the sketch to the flash and performs the update.

As soon as all the fixes are merged we will add another example that is downloading the file and performs the update.
