### ISSUE TITLE
[Feature Request] Document usage of CMSIS-DSP for Renesas based boards

### ISSUE THREAD

**Issue by pschatzmann** [arduino/ArduinoCore-renesas#17]
I was wondering if we can use functionality from CMSIS-DSP.
Any hints will be appreciated...

**Comment by aentinger** [comment]
@karlsoderby this is probably rather something to be done in a tutorial I suppose?

@pschatzmann I leave this open for now, but I think this would have been a better fit for the forum.

**Comment by pschatzmann** [comment]
So can you confirm that it is already included (eg. like in the rp2040 core) or do I need to install it as separate library like in the [Arduino Nano 33 BLE](https://store.arduino.cc/arduino-nano-33-ble) ? 
The [Arduino_CMSIS-DSP](https://github.com/arduino-libraries/Arduino_CMSIS-DSP/tree/master)  library is only working for the architectures=mbed,mbed_nano,mbed_portenta,mbed_rp2040,mbed_edge

**Comment by aentinger** [comment]
I'm not sure the Arduino_CMSIS-DIP library you've referenced is doing what you think it should do. This brings me to the most important question: I believe I have not yet fully captured what you would like to do. Can you please rephrase what outcome you'd like to achieve?

**Comment by pschatzmann** [comment]
I would like to use the FFT and the DSP Filtering functionality provided by the CMSIS DSP library.
Usually this library is made available to all ARM processors and provides some optimized DSP functionality.

**Comment by aentinger** [comment]
As per my understanding I can confirm that CMSIS DSP library is not built into the static library `libfsp.a` that's part of ArduinoCore-renesas.

![Screenshot from 2023-07-05 07-35-35](https://github.com/arduino/ArduinoCore-renesas/assets/3931733/15c90302-79ad-47c5-9010-dedb1203bbe2)

@facchinm what do you think of compiling CMSIS DSP into `libfsp.a`? [Arduino_CMSIS-DSP](https://github.com/arduino-libraries/Arduino_CMSIS-DSP/blob/master/create_lib) looks like a very custom solution made for mbed only.

**Comment by facchinm** [comment]
Hi @pschatzmann ,
[Arduino_CMSIS-DSP](https://github.com/arduino-libraries/Arduino_CMSIS-DSP/tree/master) should work everywhere, the information in library.properties is outdated.
The library can also be downloaded from Library Manager and I just tested it to work out of the box :slightly_smiling_face:

**Comment by pschatzmann** [comment]
Cool, thanks! 

I just had to adapt one include file in my library and the functionality was compiling.
Works like a charm: https://www.pschatzmann.ch/home/2023/07/10/arduino-uno-r4-fft-using-cmsis-dsp/
