### ISSUE TITLE
Not possible to install "Arduino UNO R4 Boards" from Library Manager

### ISSUE THREAD

**Issue by ingpd89** [arduino/ArduinoCore-renesas#189]
Hello everyone,

I face the following issue.
Trying to install the ""add-on" for arduino minima on IDE through the library manager from the service window i can see the message **"CRC does not correspond. File is invalid. Could be a temporary problem, tray later"** (i have translated from italian because of my ide is configured in such way but the meaning is that...). 
Someone have a workaround action?
Because it seems something blocking and i cannot use my evaluation board otherwise...

Thanks for attention.
Waiting for answare as soon as possible.

**Comment by aliphys** [comment]
Just installed the UNO R4 board package from the Arduino IDE (2.2.1).
![image](https://github.com/arduino/ArduinoCore-renesas/assets/75624145/19a933b0-31c9-4143-81f6-b2d657328916)
Could not reproduce issue. 

As a solution, you could either try later or use another network. See this comment: https://github.com/arduino/ArduinoCore-samd/issues/364#issuecomment-428777339

**Comment by umbynos** [comment]
Hello @ingpd89, could you please provide the version of the core, version of the IDE, OS, steps to reproduce?
