### ISSUE TITLE
Support for EK-RA6M5

### ISSUE THREAD

**Issue by nirmalka94** [arduino/ArduinoCore-renesas#192]
How can i Use this with EK-RA6M5 ?

**Comment by aentinger** [comment]
Short answer: you can't. A Arduino core always supports a very specific set of supported boards listed in [boards.txt](https://github.com/arduino/ArduinoCore-renesas/blob/main/boards.txt). If you have embedded background you can certainly edit the existing core to run on EK-RA6M5 or even add one as a target via PR.
