### ISSUE TITLE
`delay` function produces delay longer than argument value

### ISSUE THREAD

**Issue by gmgunderground** [arduino/ArduinoCore-renesas#194]
Look tat his discussion:

https://forum.arduino.cc/t/arduino-uno-r4-minima-wrong-delay/1190946/16

More the delay value is great more delay time is wrong

**Comment by aentinger** [comment]
Hi @gmgunderground :coffee: :wave: 

Looking at the forums thread you've already proposed a work-around. How about opening a PR for this?
