### ISSUE TITLE
Do you have a shell script to build protobuf-c.a for the ESPHost library?

### ISSUE THREAD

**Issue by JAndrassy** [arduino/ArduinoCore-renesas#212]
To cross-compile protobuf-c some number of environment variables have to be set right. 
so I guess you have a shell script somewhere?
is it available please?
I write Mbed EMAC for ESPHost and I want to make it work with Nano RP2040 Connect.

**Comment by JAndrassy** [comment]
it is just another maidnl strangeness. the ESPhost/src/cortex-m33/libprotobufc.a has only protobuf-c.c which added to ESPhost/src/protobuf-c folder compiles fast with the rest of the library. I wasted so much time on this.

**Comment by aentinger** [comment]
With #213 being merged, I'd say this issue can be considered closed - not by providing the build script, but by eliminating the need for it altogether.
