### ISSUE TITLE
Hardcoded digest algorithm value for SE05x is inconsistent with SE05x default configuration.

### ISSUE THREAD

**Issue by lagosantol** [arduino/ArduinoCore-renesas#218]
https://github.com/arduino/ArduinoCore-renesas/blob/c0f158f1e0a536de76a06163bc14d19f649ba33a/extras/tls/mbedtls_alt/ecdsa_se05x.c#L171C45-L171C45

The actual algorithm to use should depend on the input size.
(20 bytes means SHA1, 32 bytes means SHA256, etc...)

**Comment by pennam** [comment]
fixed with https://github.com/arduino/ArduinoCore-renesas/pull/229
