### ISSUE TITLE
Led Matrix : random bits on lines or columns

### ISSUE THREAD

**Issue by paulvha** [arduino/ArduinoCore-renesas#226]
When using ArduinoGraphics on the Led Matrix and doing a scroll left random bits are showing in the RIGHT columns. This is happening as well when doing a scroll up, on the bottom lines. 

It was noticed already doing development given the remark in the function `endDraw()` in `Arduino_LED_matrix.h`:

https://github.com/arduino/ArduinoCore-renesas/blob/6ee152ff2a9c00c8ab2ccff4f1eaee7e1f3388c1/libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h#L266

The root cause is related to ArduinoGraphics as it returns NEGATIVE numbers when scrolling. In the function `set()` in `Arduino_led_matrix.h` it checks for out of bound values, BUT not for negative values for Y and X. Then when doing a `_canvasBuffer[y][x]` will cause under desired memory to be written.

**_Solution :_**

change in function `set()`,  line 251 from:

https://github.com/arduino/ArduinoCore-renesas/blob/6ee152ff2a9c00c8ab2ccff4f1eaee7e1f3388c1/libraries/Arduino_LED_Matrix/src/Arduino_LED_Matrix.h#L251

to:

```cpp[
if (y >= canvasHeight || x >= canvasWidth || y < 0 || x < 0) {
```

**Comment by aentinger** [comment]
Hi @paulvha :coffee: :wave: 

Thank you for reporting this issue. I've been able to verify it with this minimal example sketch:

```C++
// To use ArduinoGraphics APIs, please include BEFORE Arduino_LED_Matrix
#include "ArduinoGraphics.h"
#include "Arduino_LED_Matrix.h"

ArduinoLEDMatrix matrix;

void setup() {
  Serial.begin(115200);
  matrix.begin();

  matrix.textScrollSpeed(50);

  matrix.beginDraw();
  matrix.stroke(0xFFFFFFFF);

  const char text[] = "UNO r4";
  matrix.textFont(Font_4x6);
  matrix.beginText(0, 1, 0xFFFFFF);
  matrix.println(text);
  matrix.endText(SCROLL_LEFT);

  matrix.endDraw();

  delay(2000);
}

void loop() {
}
```

I can confirm that your suggestion is fixing this issue and I will be preparing a PR for it.
