### ISSUE TITLE
WiFi.ping() function on WiFiS3 library doesn't exist

### ISSUE THREAD

**Issue by gpb01** [arduino/ArduinoCore-renesas#251]
The WiFi.ping() function, that exists in the library [WiFiNINA](https://github.com/arduino-libraries/WiFiNINA/blob/12c33f10cc3eddad245a2263fe0476fee60320a2/src/WiFi.cpp#L379), **doesn't exist** in the WiFiS3 library and there is no way to ICMP ping network devices.

Can you please add such a function?

#### Additional requests

- https://github.com/arduino/ArduinoCore-renesas/issues/251#issuecomment-1941934908
- https://github.com/arduino/ArduinoCore-renesas/issues/251#issuecomment-2144226026
- https://github.com/arduino/ArduinoCore-renesas/issues/251#issuecomment-2179502075

**Comment by TeubyDE** [comment]
would be really nice to have this feature!

**Comment by paulvha** [comment]
I have taken some time to include PING. It requires updates in both WiFiS3 as well as the UNOR4USBBridge-software. In the attached document I have documented the changes to be made.
[add_PING.docx](https://github.com/arduino/ArduinoCore-renesas/files/14284289/add_PING.docx)

**Comment by paulvha** [comment]
I have spend time to add PING. it requires changes to both the UNOR4Bridge software as well as the WiFiS3 library. In the attached zip is a document with the changes to be applied. Also the files that need changes are included for reference.
[WiFiPing.zip](https://github.com/arduino/ArduinoCore-renesas/files/14284384/WiFiPing.zip)

regards,
Paul

**Comment by gpb01** [comment]
> In the attached zip is a document with the changes to be applied.

Hi Paul,
thanks a lot for your work, but ... if you don't create a "_fork_" and do an official "_pull request_" ... I don't know if the Arduino team will consider it ... :-\ 

Guglielmo

**Comment by paulvha** [comment]
hi Guglielmo,
I had considered doing that, but I am not sure the Arduino Team is interested. Several other pending bridge issues could be solved and some don't look that difficult to solve. I was doing this exercise to understand how the bridge software is working. It took longer time to get started as good documentation was missing and different links & scripts were outdated. 

regards,
Paul

**Comment by JAndrassy** [comment]
@paulvha they are interested. I have now 23 PR merged in core and 3 in firmware

**Comment by paulvha** [comment]
I can make a fork and pull request if interested.  I also saw noticed update to the partition table for the ESP32 (i used the latest version from yesterday). I have made a pull request for the firmware and will add one for the core.  Did you also solve the getTime() issue 206?

regards
Paul

**Comment by privitera** [comment]
Wondering, what is the status of this?

**Comment by voidzero** [comment]
I just got my first R4 and am very excited to try this out. Thanks for the pull request, hope it will be accepted.
