### ISSUE TITLE
"Please run as root" msg during install

### ISSUE THREAD

**Issue by LightningStalker** [arduino/ArduinoCore-renesas#333]
AppImage version
No indications but appears to be the post_install.sh
Running IDE suid or sudo -s homes as root instead of user home
`sudo -s echo $HOME` = /home/user

**Comment by per1234** [comment]
Hi @LightningStalker.

> appears to be the post_install.sh

That is correct:

https://github.com/arduino/ArduinoCore-renesas/blob/711ef1d278a5e71fd91b65b09607eecea34ba837/post_install.sh#L13

> Running IDE suid or sudo -s homes as root instead of user home

Yeah, you should not run Arduino IDE as superuser. I think this message was intended for those who are running the script directly from the terminal. However, when it is shown by Arduino IDE the message is misleading and unhelpful.

I submitted a proposal to make the output more friendly: https://github.com/arduino/ArduinoCore-renesas/pull/334
