### ISSUE TITLE
Mouse library opens DFU port

### ISSUE THREAD

**Issue by dyw8e8e8** [arduino/ArduinoCore-renesas#345]
When I include the official mouse library in my sketch and upload it to my arduino uno r4 wifi it seems to put it in partial DFU mode - that being, that the sketch functions as intended, but a DFU port opens on the board. I'd really appreciate some advice as to why this happens, and whether it can be prevented.

```
#include` <Mouse.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

![image](https://github.com/arduino/ArduinoCore-renesas/assets/138831472/93c2dc62-0663-4df4-bd15-5a85507988cf)

**Comment by per1234** [comment]
Hi @dyw8e8e8. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/hardware/uno-r4/uno-r4-wifi/189
