### ISSUE TITLE
Serial.printf support

### ISSUE THREAD

**Issue by kakopappa** [arduino/ArduinoCore-renesas#351]
I noticed Serial does not support `Serial.printf`. This is what I have done so far. could be wrong Please correct me if I am wrong here.

in `Print.h`

`size_t printf(const char *format, ...);`

in `Print.cpp`

```
#include <stdarg.h> // Required for va_list, va_start, va_end
.....

size_t Print::printf(const char *format, ...) {
  va_list arg;
  va_start(arg, format);
  size_t ret = vprintf(format, arg);
  va_end(arg);
  return ret;
}
```

**Comment by per1234** [comment]
Closing as off topic since the `Print` class is not implemented in this repository, but instead in https://github.com/arduino/ArduinoCore-API.

We already have a request in that repository: https://github.com/arduino/ArduinoCore-API/issues/32
