### ISSUE TITLE
UNO R4: Add support for CAN Standard Frame Format (in addition to EFF)

### ISSUE THREAD

**Issue by srolf** [arduino/ArduinoCore-renesas#36]
Please add in the UNO R4 CAN library the support for transmit/receive of CAN frames also in SFF.

Preferred would be an own parameter in the message creation which allows to define either SFF (maybe the default) or EFF.

Adding a hint towards the current CAN tutorials would be helpful, because it's not directly obvious to be forced/limited to EFF.

CAN 2.0A defines SFF.
CAN 2.0B defines EFF.
Most of the available MCP2515 libs are supporting SFF and EFF.
CAN on Arduino Due by "due_can" lib supports SFF and EFF.
In the automotive area SFF for communication is very common.

**Comment by Lesani** [comment]
@aentinger please please please

**Comment by designer2k2** [comment]
+1 also from me for this!

The R4 is sitting now idle due to this, for me in automotive things its useless with only extended frame support.

Is anybody working on this? Or is there information around on how to add it?

**Comment by aentinger** [comment]
Your feature request(s) has been noted. I'll try to get some time scheduled for extending software-support for 11-Bit IDs.

**Comment by srolf** [comment]
> Your feature request(s) has been noted. I'll try to get some time scheduled for extending software-support for 11-Bit IDs.

Thank you very much!

Out of curiosity: Maybe not possible, but I'm wondering if the CAN TXD/RXD pins can be remapped or are they "hard-wired"? Background: I was thinking about using a Minima and the [Ethernet Shield Rev2](https://store.arduino.cc/products/arduino-ethernet-shield-2) to create a gateway CAN<->ETH, but without remapping, but I would expect issues with the SD-card reader on that shield.

**Comment by aentinger** [comment]
> Maybe not possible, but I'm wondering if the CAN TXD/RXD pins can be remapped or are they "hard-wired"?

They can also be remapped to (some) other pins, the key is to search [pinmux.inc](https://github.com/arduino/ArduinoCore-renesas/blob/main/variants/MINIMA/pinmux.inc) for `PIN_CAN_TX `and `PIN_CAN_RX`. However, as the CAN objects are instantiated in the library (i.e. [here](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/Arduino_CAN/src/R7FA4M1_CAN.cpp#L328)) you'd need to change the library to change the pin-mapping.

**Comment by srolf** [comment]
> you'd need to change the library to change the pin-mapping

Got it, thanks. I should work on my C++ skills... an alternative begin() would be helpful.

**Comment by Lesani** [comment]
> > you'd need to change the library to change the pin-mapping
> 
> Got it, thanks. I should work on my C++ skills... an alternative begin() would be helpful.

You should make a separate Feature Request to keep the two topics clean. In my use case I don't need different pins, but I agree, if the hardware can do it, it should be configurable somehow.

**Comment by Lesani** [comment]
> Your feature request(s) has been noted. I'll try to get some time scheduled for extending software-support for 11-Bit IDs.

Thank you!

**Comment by aentinger** [comment]
> Got it, thanks. I should work on my C++ skills... an alternative begin() would be helpful.

@srolf please create a separate feature request.

**Comment by aentinger** [comment]
Heads up everyone, mixed mode (supporting both 11-Bit standard CAN IDs and 29-Bit extended CAN IDs) is now being supported for Arduino Uno R4 `WiFi` and `Minima`. If you want to take a sneak preview take a look at https://github.com/arduino/ArduinoCore-renesas/pull/79 .

**Comment by srolf** [comment]
Thank you, a Minima with TJA1051 and tiny OLED is still standing here :-)
