### ISSUE TITLE
where the "bootloaders /UNO_R4" esp32's source code?

### ISSUE THREAD

**Issue by sunduoze** [arduino/ArduinoCore-renesas#361]
I want to watch the bootloader source code about UNO R4, thanks!

**Comment by JAndrassy** [comment]
it is UNOR4USBBridge in [extras](https://github.com/arduino/ArduinoCore-renesas/tree/main/extras)

https://github.com/arduino/uno-r4-wifi-usb-bridge/tree/a634856e5467022bc7587e7c8a856811255ea890/UNOR4USBBridge
