### ISSUE TITLE
CLA assistant fails, and blocks the pull request

### ISSUE THREAD

**Issue by drmcnelson** [arduino/ArduinoCore-renesas#363]
I have submitted a pull request.

CLA assistant appeared and asks that I sign a form.  I signed the form, or so it appeared.

CLA assistant then sends me a message and insists on access to my private data.

That is not going to happen, ever.

If you want contributions, you will have to get this straightened out with CLA assistant.

**Comment by per1234** [comment]
Hi @drmcnelson. I'm sorry if you aren't satisfied with the [CLA assistant service](https://cla-assistant.io/). Arduino is only a user of that service so there is nothing we can do to resolve your problem. So I'll close this as off topic for this issue tracker.
