### ISSUE TITLE
Please push framework updates to platformIO registry

### ISSUE THREAD

**Issue by pisto** [arduino/ArduinoCore-renesas#380]
I would like to use the latest releases of this Arduino framework in PlatformIO (https://registry.platformio.org/tools/platformio/framework-arduinorenesas-portenta/ and https://registry.platformio.org/tools/platformio/framework-arduinorenesas-uno). Currently, uploaded libraries in the PlatformIO are lagging behind, stuck at version 1.1.0. I am guessing that one of the owners here just need to push the updated library to the registry, is that correct?

After that, I'll open a pull request on https://github.com/platformio/platform-renesas-ra to reference the newer versions.

**Comment by per1234** [comment]
Hi @pisto. The developers of this platform don't have any involvement with PlatformIO. Any support for these boards in PlatformIO is provided exclusively by the PlatformIO company and community, so it is up to them to pull any changes. You are welcome to contribute that work yourself, or take it up with the PlatformIO folks, but such requests are off topic for this repository's issue tracker so I'll close this.
