### ISSUE TITLE
ArduinoBLE Support

### ISSUE THREAD

**Issue by SnooBama** [arduino/ArduinoCore-renesas#40]
Can't find support for ArduinoBLE library. Will it be supported on Arduino UNO R4 WiFi boards? ESP32-S3-MINI-1 has BLE&B5 in it.

**Comment by facchinm** [comment]
Hi @SnooBama ,
the PR for UNO R4 support is here https://github.com/arduino-libraries/ArduinoBLE/pull/305 , we are waiting to merge to make sure the fw update procedure works fine for everyone :slightly_smiling_face: 
In case you want to try it, please follow the instructions [here](https://github.com/arduino/uno-r4-wifi-usb-bridge/tree/main/unor4wifi-updater) to update the firmware.
