### ISSUE TITLE
Configuring RX FIFO Instead of RX Buffers on Portenta C33 with Arduino_CAN Library

### ISSUE THREAD

**Issue by NassRami** [arduino/ArduinoCore-renesas#416]
Hello,

I am currently working with the Portenta C33 using the Arduino_CAN library from Renesas. I am using RX Buffers to read incoming CAN data, but I am encountering an issue where too many frames are arriving at once. As a result, at certain moments, I read incorrect values.

I would like to configure the system to generate interrupts and switch from using RX Buffers to an RX FIFO for better handling of the incoming CAN messages.

Could you please guide me on how to configure the RX FIFO correctly with the Arduino_CAN library? Additionally, I am using PlatformIO as my development environment.

Thank you in advance for your support.

**Comment by per1234** [comment]
Hi @NassRami. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by per1234** [comment]
No, this is not a place for discussions. This is only a place to submit formal bug reports and feature requests. You are requesting assistance with your project. The appropriate place to request project assistance is on Arduino Forum. In addition, PlatformIO doesn't directly use Arduino boards platforms, so questions related to the use of PlatformIO are doubly off topic here.
