### ISSUE TITLE
Upload broken for the Uno R4 WiFi on Windows 11 (Still Broken)

### ISSUE THREAD

**Issue by mjs513** [arduino/ArduinoCore-renesas#62]
While uploading to the WiFi board I keep having issues with it returning errors about not finding com port and can not upload even though the Wifi Board is shown in the boards menu along with the com port:
![Screenshot 2023-07-21 163518](https://github.com/arduino/ArduinoCore-renesas/assets/5366213/b1e54592-81b7-4224-8332-9cd54c76a66c)

It appears to be hit or miss on whether it works - mostly misses.  Sometimes it will work if I replug the board in several times most not.    Happens even with blink.  Not sure it is related to the PR #10, https://github.com/arduino/ArduinoCore-renesas/issues/10.  At time of this writing none of these things work and stuck.

Note: Must have loaded a few dozen times before this issue cropped up

System:
```
Edition	Windows 11 Home
Version	22H2
Installed on	‎7/‎8/‎2023
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0
```

Arduino Version:  2.1.1 Released
```
Version: 2.1.1
Date: 2023-06-30T16:04:40.277Z
CLI Version: 0.32.3
```

happens with Minima as well but can usually recover the minima by hitting reset twice and then uploading.

EDIT:  Also just went through this.

**Comment by mjs513** [comment]
Update:  This fix seems to get it working but took a few tries to get the timing right: https://forum.arduino.cc/t/problem-uploading-to-board/1142928/34 - see my response in post #35

**Comment by mjs513** [comment]
When the issues are occurring is when I have several devices hanging off the I2C buses.  Unplugging everything and doing the fix that @KurtE mentioned on the forum uploads are working no issue.  A bit concerned now if the issue is too much current being drawn on the pins or something wrong with I2C.

**Comment by Plinfa** [comment]
Hi, is there a slight chance that someone else is experiencing a similar behaviour on Mac OS Ventura 13.5?

Port, as well as Board are selected automatically, however the upload always fails: 

No device found on cu.usbmodem ...
Failed uploading: uploading error: exit status 1

Already checked if another Application blocks the port, sadly this was not the case - re-install IDE 2.11 / Board did also not help.

**Comment by mjs513** [comment]
@Plinfa - if you look on the Arduino Uno R4 forum you will see there are lots of folks having the same type of issues on all platorms.   Seems to worse if you update the firmware

**Comment by Plinfa** [comment]
@mjs513 thanks for the info. Found a workaround on one of those sites. Pressing the reset button halfway through compiling solves the issue. Since then, I had no connection problems at all - I assume as soon as  the sketch is being closed and re-opened, it will fail again.

**Comment by pennam** [comment]
@mjs513 @Plinfa what WiFi firmware version are you using on your boards? `0.1.0` or `0.2.0`?

**Comment by mjs513** [comment]
@pennam - been testing on the minima, Wifi 0.1.0, and 0.2.0 (have 2 boards).  Was kind of giving up on Wifi because of the uploading issues.

**Comment by pennam** [comment]
@mjs513 is upload failing with both `0.1.0` and `0.2.0`? Are your boards from the early access program?

**Comment by KurtE** [comment]
Sorry I am not @mjs513 and only have one wifi board, currently at 0.2.0.  I had a few times with the 0.1 version that failed to upload.  Most of the time it was easy to rectify. double click reset, make sure no other windows open with Serial port, etc.

After update to .2, the upload failures happen a lot more, and resolving them, a lot trickier.  I suspect that there are timing windows in the code, where it works and where it does not, and you just have to hit it right.

**Comment by pennam** [comment]
@KurtE Thanks for your feedback!

@mjs513 @Plinfa @KurtE  We have just made a pre-release of a new firmware `0.2.1` that should solve the issue. Do you mind give it a spin? You can download the updater package from here:

* [windows](https://github.com/arduino/uno-r4-wifi-usb-bridge/releases/download/0.2.1-rc1/unor4wifi-update-linux.zip)
* [macos](https://github.com/arduino/uno-r4-wifi-usb-bridge/releases/download/0.2.1-rc1/unor4wifi-update-macos.zip)
* [linux](https://github.com/arduino/uno-r4-wifi-usb-bridge/releases/download/0.2.1-rc1/unor4wifi-update-linux.zip)

**Comment by mjs513** [comment]
@pennam - just tried to download the windows version but it the zip file name is -update-linux.zip?   Don't think thats correct

**Comment by pennam** [comment]
> @pennam - just tried to download the windows version but it the zip file name is -update-linux.zip? Don't think thats correct

@mjs513 i've fixed the link!

**Comment by mjs513** [comment]
@pennam 
1. update.bat ran smoothly (note this is on a wifi board running 0.1.0
2.  Just updated from 0.2.0 to 0.2.1 no issues.  But why Adafruit Qt Py ESP32-C3 after upload :) until I unplugged it and replugged it back in

Uploaded a few the sketches I used that had issues and looks like the fix is working. Only time will tell but feels right.  As I said so far so good!!!!  Nice work.

PS.  Looks like it fixed the issue I was having with it loosing the output to serial port when opening and closing it.

**Comment by pennam** [comment]
Thanks for the test @mjs513 ! :rocket: 

> But why Adafruit Qt Py ESP32-C3 after upload 

After the update the board is still in ESP mode so the IDE feels a bit confused about the reported VID and PID. After a wifi firmware update you always have to unplug and replug the board from your PC.

> Only time will tell but feels right.

Please let me know if you encounter other upload issues during your tests.

**Comment by mjs513** [comment]
@pennam - @KurtE 

Well so far the only time I have been able to make it fail an upload (note this was intentional test to see what would happen) was when I was opening and closing the Serial Monitor while it was trying to upload - basically came back with serial port busy so must have timed it just right while the IDE was trying to connect and DFU was trying to connect as well.

But must have uploaded a couple of dozen of times with the serial monitor open (and spewing data) and closed without a failure to upload.  I even tried the sketch that was posted that the person said would fail all the time :).

Not sure what else to try - all the sketches that I had that would give the issues seem to be non-issues now.  Maybe @KurtE gives it try he can see if he any problems.

**Comment by KurtE** [comment]
I have updated now... And a have done a few uploads.  So far so good

**Comment by mjs513** [comment]
Was uploading sketches to the wifi board most of the afternoon/night as well and have not hit an issue about it failing to upload.  Think you got it fixed.

**Comment by Plinfa** [comment]
@pennam just updated to 0.2.1 - no issues when uploading since then. Seems to work. 

Thanks for your tremendous effort on fixing those Bugs. :)
