### ISSUE TITLE
compatibility - Consider shipping an empty wiring_private.h

### ISSUE THREAD

**Issue by KurtE** [arduino/ArduinoCore-renesas#72]
There are several libraries out there, like most of the Adafruit display libraries for whatever reason include this file.
Obviously, the library owners can add some additional #if type statements to avoid this in this case, but you probably will get forum threads for a lot of these libraries, like Adafruit_ILI9341, that can easily be solved by simply putting in a blank file.  Or maybe one with a #warning

Just a thought.

There may be other such files that should be considered as well.

**Comment by aentinger** [comment]
In an ideal world (I'm well aware that we live in the real world, but let's keep some goal in mind), internal "private" files should not be used by 3rd party vendors. Please consider opening an issue report or PR at the affected repositories. We can not provide workarounds for what constitute API violations in the first place.
