### ISSUE TITLE
SCL is incorrectly defined in variants (pins_arduino.h)

### ISSUE THREAD

**Issue by bperrybap** [arduino/ArduinoCore-renesas#81]
The pins_arduino.h header files in MIMINA and UNOWIFIR4 directories are incorrectly defining the SCL symbol.
They are defining the SCL pin to be same as the SDA pin.
To fix this the pins_arduino.h header files for both/all variants 
will need to change this:
```
static const uint8_t SDA = WIRE_SDA_PIN;
static const uint8_t SCL = WIRE_SDA_PIN;
```
to this
```
static const uint8_t SDA = WIRE_SDA_PIN;
static const uint8_t SCL = WIRE_SCL_PIN;
```

**Comment by aentinger** [comment]
Good catch! Thank you @bperrybap :coffee: :wave: :bow:
